% -*- mode: tex -*-
\title{fastbeta: Tools for Back-Calculating Infectious Disease
  Transmission Rates}
\author{by Mikael Jagan and David Earn}
\maketitle

\newcommand{\mj}[1]{{\color{teal} [MJ: #1]}}
\newcommand{\de}[1]{{\color{purple} [DE: #1]}}

\abstract{ % An abstract of less than 150 words.
  Infectious disease transmission rates vary over time due to temporal
  changes in the environment, host population behaviour, and pathogen
  characteristics such as transmissibility and virulence.  Variation in
  the transmission rate is not observed directly but has a large effect
  on patterns of recurrent epidemics, motivating algorithms for
  estimating transmission rates from time series of observed case
  counts.  Rigorous statistical algorithms, such as iterated filtering,
  are well documented but computationally expensive, tending to scale
  poorly to longer time series.  Here, we present an \R{} package,
  \CRANpkg{fastbeta}, that implements a fast, non-probabilistic
  algorithm for back-calculating time-varying transmission rates from
  incidence time series.  We highlight additional tools provided by the
  package, including a function for efficient SEIR model simulation and
  an implementation of the Richardson-Lucy deconvolution used to
  recover incidence from reported incidence conditioned on a delay
  distribution.
  %% If we can devise a fastbeta-pomp example, then we should include
  %% it and mention it here.
}

<<init, echo=FALSE>>=
fig.count <- 0L
fig.tex <- NULL
fig.pdf <- NULL
fig.par <- NULL
fig.begin <-
function(...) {
    fig.count <<- fig.count + 1L
    fig.tex <<- sprintf("figure-%02d.tex", fig.count)
    fig.pdf <<- sprintf("figure-%02d.pdf", fig.count)
    tikzDevice:::tikz(filename = fig.tex, standAlone = TRUE, ...)
    fig.par <<- par(las = 1, mgp = c(2.5, 0.5, 0), tcl = -0.2,
                    xaxs = "i", yaxs = "i")
    invisible(NULL)
}
fig.end <-
function() {
    par(fig.par)
    dev.off()
    tools:::texi2pdf(fig.tex)
    invisible(NULL)
}
@

\section{Introduction}

%% Rt: EpiNow2, EpiEstim, EpiLPS, R0,
%%         nbTransmission, ern, Bernadette, ... ??
%% beta: fastbeta, Bernadette, ... ??
%% generic: macpan2, CollocInfer, pomp
%% even more generic: numerical integration + optim

Estimation, simulation, and analysis of compartmental mathematical
models are fundamental tasks in infectious disease epidemiology.
A critical parameter of any such model is the infectious disease
transmission rate, measuring how readily a disease spreads within a
host population.  The transmission rate changes over time in response
to factors such as weather, public health interventions, and pathogen
evolution, and these changes can have a profound influence on disease
dynamics---on the number of people infected during an epidemic, the
time scale over which an epidemic occurs, and patterns of epidemic
recurrence.  Accordingly, accurate knowledge of the transmission rate
can be used to calibrate epidemic forecasts, to inform public health
planning, and to discriminate between hypotheses about the mechanisms
that give rise to observed dynamics.

A barrier to practical consideration of transmission rates is
uncertainty.  Direct observation requires knowledge of the chain of
transmission---who infected whom and when---which is rarely available
outside of sexually transmitted diseases of humans.  In practice, the
transmission rate as a function of time must be estimated as a latent
variable from time series of observed disease incidence (counts of
infections) or disease mortality (counts of deaths from infection).




\section{The \texorpdfstring{$SE^{m}I^{n}R$}{SE\{m\}I\{n\}R} model}
\label{sec:seir}

The algorithm for transmission rate back-calculation implemented in
\CRANpkg{fastbeta} assumes that spread of the infectious disease of
interest in the population of interest can be represented by a
compartmental $SE^{m}I^{n}R$ model formulated with time-varying rates of
birth, death, and transmission---that is, an $SEIR$ model in which the
$E$ and $I$ compartments are partitioned into $m$ and $n$ stages,
respectively, for positive integers $m$ and $n$.  As a system of
ordinary differential equations, this model is expressed as
%
\begin{subequations}
\label{eq:seir}
\begin{align}
  \frac{\text{d} S}{\text{d} t}
  &= \nu(t) + \delta R - \beta(t) S \sum\nolimits_{j} I^{j} - \mu(t) S \\
  \frac{\text{d} E^{1}}{\text{d} t}
  &= \beta(t) S \sum\nolimits_{j} I^{j} - m \sigma E^{1} - \mu(t) E^{1} \\
  \frac{\text{d} E^{i}}{\text{d} t}
  &= m \sigma E^{i-1} - m \sigma E^{i} - \mu(t) E^{i} \\
  \frac{\text{d} I^{1}}{\text{d} t}
  &= m \sigma E^{m} - n \gamma I^{1} - \mu(t) I^{1} \\
  \frac{\text{d} I^{j}}{\text{d} t}
  &= n \gamma I^{j-1} - n \gamma I^{j} - \mu(t) I^{j} \\
  \frac{\text{d} R}{\text{d} t}
  &= n \gamma I^{n} - \delta R - \mu(t) R
\end{align}
\end{subequations}
%
where $S$, $E=\sum_{i=1}^{m} E^{i}$, $I=\sum_{j=1}^{n} I^{j}$, and $R$
are the numbers of individuals who are susceptible, exposed (infected
and not infectious), infectious, and recovered with immunity,
respectively, so that $N = S + E + I + R$ is the population size.

The functional parameters are $\nu(t) \geq 0$, the birth rate;
$\mu(t) \geq 0$, the natural mortality rate; and $\beta(t) \geq 0$, the
transmission rate.  The constant parameters are $\sigma > 0$,
$\gamma > 0$, and $\delta \geq 0$.  $\delta$ is a rate of loss of
immunity, allowing for reinfection of recovered individuals.

Equations \eqref{eq:seir} admit a corresponding continuous time Markov
process, in which the latent and infectious periods conditioned on
survival until recovery are Erlang-distributed with means $1/\sigma$ and
$1/\gamma$:
%
\begin{subequations}
\label{eq:erlang}
\begin{align}
  T_\text{lat} \sim& \mathrm{Erlang}(k=m, \lambda=m \sigma) \\
  T_\text{inf} \sim& \mathrm{Erlang}(k=n, \lambda=n \gamma)
\end{align}
\end{subequations}
%
The probability density function corresponding to
$\mathrm{Erlang}(k, \lambda)$ (a restriction of the gamma family
$\mathrm{Gamma}(k, \lambda)$ to integer $k$) is given by
%
\begin{equation}
\label{eq:erlang-pdf}
f(\tau; k, \lambda) = \frac{\lambda^{k}}{(k - 1)!} \tau^{k - 1} \exp(-\lambda \tau)\,,\quad k \in \{1, 2, \dots\}\,, \lambda > 0
\end{equation}
%
(see Figure~\ref{fig:erlang-pdf}).
%
<<erlang-pdf, echo=FALSE>>=
fig.begin(width = 6, height = 3)
x <- seq.int(0, 4, by = 0.01)
k <- 1:8
s <- matrix(k, nrow = length(x), ncol = length(k), byrow = TRUE)
y <- dgamma(x, shape = s, rate = s)
matplot(x, y, type = "n",
        xlab = "$\\tau$", ylab = "density, $f(\\tau; k, \\lambda)$")
abline(v = 1)
matlines(x, y, lwd = 2, lty = 1:5, col = 2:7)
legend("topright", lwd = 2, lty = 1:5, col = 2:7,
       bty = "n", cex = 0.8, legend = sprintf("$k = %d$", k))
fig.end()
@
\begin{figure}[h]
  \centering
  \includegraphics{\Sexpr{fig.pdf}}
  \caption{Probability density function, $f(\tau; k, \lambda)$, of the
    Erlang distribution with shape parameter $k$ and rate parameter
    $\lambda = k \alpha$, for $k \in \{1, \ldots, 8\}$ and $\alpha = 1$.
    Here, the mean $\tau = k / \lambda$ is fixed and equal to 1.}
  \label{fig:erlang-pdf}
\end{figure}
%
Setting $m = n = 1$, one recovers as a special case the traditional
$SEIR$ model with exponentially distributed stage durations:
%
\begin{subequations}
\label{eq:erlang}
\begin{align}
  T_\text{lat} \overset{m = 1}{\sim}& \mathrm{Exponential}(\lambda=\sigma) \\
  T_\text{inf} \overset{n = 1}{\sim}& \mathrm{Exponential}(\lambda=\gamma)
\end{align}
\end{subequations}
%
Partitioning of the exposed and infectious compartments by
\CRANpkg{fastbeta} frees the user from the conventional but strong
assumption that the stage durations are exponentially distributed.

\CRANpkg{fastbeta} supports a limiting case of the $SE^{m}I^{n}R$ model,
namely $\sigma \to \infty$.  In this case, one obtains an $SI^{n}R$
model in which onset of infectiousness is immediate and not delayed by a
latent period:
%
\begin{subequations}
\label{eq:sir}
\begin{align}
  \frac{\text{d} S}{\text{d} t}
  &= \nu(t) + \delta R - \beta(t) S \sum\nolimits_{j} I^{j} - \mu(t) S \\
  \frac{\text{d} I^{1}}{\text{d} t}
  &= \beta(t) S \sum\nolimits_{j} I^{j} - n \gamma I^{1} - \mu(t) I^{1} \\
  \frac{\text{d} I^{j}}{\text{d} t}
  &= n \gamma I^{j-1} - n \gamma I^{j} - \mu(t) I^{j} \\
  \frac{\text{d} R}{\text{d} t}
  &= n \gamma I^{n} - \delta R - \mu(t) R
\end{align}
\end{subequations}

\section{The observation model}
\label{sec:obs}

Transmission rate back-calculation depends on the availability of an
equally spaced time series of disease incidence containing counts of the
number of infections between successive time points.  In practice,
incidence is not observed directly and must instead be estimated from
\emph{reported} incidence, which counts the number of cases reported
between successive time points.  \CRANpkg{fastbeta} assumes a general
model for the relationship between incidence and reported incidence.
Let $X_{i}$ and $Y_{i}$ be the number of infections and cases reported,
respectively, during time step $i$.  Then:
%
\begin{equation}
  \label{eq:obs}
  X_{i}
\end{equation}
%

\subsection{Arguments}

\begin{description}
\item[\code{length.out}] \hfill \\
  a non-negative integer indicating the time series length.
\item[\code{beta, nu, mu}] \hfill \\
  functions of one or more arguments returning transmission, birth, and
  natural death rates at the time point indicated by the first argument.
  Arguments after the first must be strictly optional.  The functions
  need not be vectorized.
\item[\code{sigma, gamma, delta}] \hfill \\
  non-negative numbers.  \code{m*sigma}, \code{n*gamma}, and
  \code{delta} are the rates of removal from each latent, infectious,
  and recovered compartment.
\item[\code{m}] \hfill \\
  a non-negative integer indicating a number of latent stages.
\item[\code{n}] \hfill \\
  a positive integer indicating a number of infectious stages.
\item[\code{init}] \hfill \\
  a numeric vector of length \code{1+m+n+1} giving an initial state with
  compartments ordered as $(S, E, I, R)$.
\item[\code{stochastic}] \hfill \\
  a logical indicating if the simulation should be stochastic.
\item[\code{prob}] \hfill \\
  a numeric vector of length \code{n} such that \code{prob[i]} is the
  probability that an infection during interval \code{i} is eventually
  observed.  \code{prob} of length 1 is recycled.
\item[\code{delay}] \hfill \\
  a numeric vector of positive length such that \code{delay[i]} is the
  probability that an infection during interval \code{j} is observed
  during interval \code{j+i-1}, given that it is eventually observed.
  \code{delay} need not sum to 1 but must not sum to 0.
\item[\code{aggregate}] \hfill \\
  a logical indicating if latent and infectious compartments should be
  aggregated.
\item[\code{useCompiled}] \hfill \\
  a logical indicating if derivatives should be computed by compiled
  C functions rather than by \R{} functions (which \emph{may} be
  \emph{byte}-compiled).  Set to \code{FALSE} only if \code{TRUE}
  seems to cause problems, and in that case please report the problems
  with \code{bug.report(package = "fastbeta")}.
\item[\code{\ldots}] \hfill \\
  optional arguments passed to \CRANpkg{deSolve}\code{::lsoda} (directly)
  or \CRANpkg{adaptivetau}\code{::ssa.adaptivetau} (via its list argument
  \code{tl.params}), depending on \code{stochastic}.
\end{description}

\subsection{An example}

<<seir-ex-1>>=
library(fastbeta)
beta <- function (t, a = 1e-01, b = 1e-05) b * (1 + a * sinpi(t / 26))
nu   <- function (t) 1e+03
mu   <- function (t) 1e-03

sigma <- 0.5
gamma <- 0.5
delta <- 0

init <- c(S = 50200, E = 1895, I = 1892, R = 946011)

length.out <- 250L
prob <- 0.1
delay <- diff(pgamma(0:8, 2.5))

set.seed(0L)
X <- seir(length.out, beta, nu, mu, sigma, gamma, delta, init = init,
          prob = prob, delay = delay, epsilon = 0.002)
##                                                 ^^^^^^^
## default epsilon = 0.05 allows too big leaps => spurious noise
##
str(X)

fig.begin(width = 6, height = 6)
plot(X)
fig.end()
@
\begin{figure}[h]
  \centering
  \includegraphics{\Sexpr{fig.pdf}}
  \caption{\CRANpkg{fastbeta}\code{::seir} example.}
  \label{fig:seir-ex}
\end{figure}
<<seir-ex-2>>=
r <- 10L
Y <- do.call(cbind, replicate(r, simplify = FALSE,
	seir(length.out, beta, nu, mu, sigma, gamma, delta, init = init,
	     prob = prob, delay = delay, epsilon = 0.002)[, "Z.obs"]))
str(Y)

fig.begin(width = 6, height = 3)
plot(window(Y, start = tsp(Y)[1L] + length(delay) / tsp(Y)[3L]),
     ##        ^^^^^
     ## discards points showing edge effects due to 'delay'
     ##
     plot.type = "single", col = seq_len(r), ylab = "Case reports")
fig.end()
@
\begin{figure}[h]
  \centering
  \includegraphics{\Sexpr{fig.pdf}}
  \caption{\CRANpkg{fastbeta}\code{::seir} example.}
  \label{fig:seir-ex}
\end{figure}

\section{Back-calculating the transmission rate from incidence}

In model \eqref{eq:seir}, the transmission rate $\beta$ and compartment
sizes $S$, $E^{i}$, $I^{j}$, and $R$ are not directly observed.
\CRANpkg{fastbeta}\code{::fastbeta} implements an iterative algorithm
for back-calculating their values at discrete time points, provided
equally spaced time series of three variables that tend to be either
observed or readily estimated, namely disease incidence,
%
\begin{equation}
Z_{t} = \int_{t - 1}^{t} \beta(s) S(s) \sum_{j=1}^{n} I^{j}(s)\,\text{d}s\,,
\end{equation}
%
births,
%
\begin{equation}
B_{t} = \int_{t - 1}^{t} \nu(s)\,\text{d}s\,,
\end{equation}
%
and the natural mortality rate $\mu_{t} = \mu(t)$.  The iteration is
given by
%
\begin{subequations}
\label{eq:fastbeta}
\begin{align}
  E_{t+1}^{1} &= \frac{(1 - \frac{1}{2} (m \sigma + \mu_{t})) E_{t}^{1} + Z_{t+1}}{1 + \frac{1}{2} (m \sigma + \mu_{t+1})} \\
  E_{t+1}^{i} &= \frac{(1 - \frac{1}{2} (m \sigma + \mu_{t})) E_{t}^{i} + \frac{1}{2} m \sigma (E_{t}^{i-1} + E_{t+1}^{i-1})}{1 + \frac{1}{2} (m \sigma + \mu_{t+1})} \\
  I_{t+1}^{1} &= \frac{(1 - \frac{1}{2} (n \gamma + \mu_{t})) I_{t}^{1} + \frac{1}{2} m \sigma (E_{t}^{m} + E_{t+1}^{m})}{1 + \frac{1}{2} (n \gamma + \mu_{t+1})} \\
  I_{t+1}^{j} &= \frac{(1 - \frac{1}{2} (n \gamma + \mu_{t})) I_{t}^{j} + \frac{1}{2} n \gamma (I_{t}^{j-1} + I_{t+1}^{j-1})}{1 + \frac{1}{2} (n \gamma + \mu_{t+1})} \\
  R_{t+1} &= \frac{(1 - \frac{1}{2} (\delta + \mu_{t})) R_{t} + \frac{1}{2} n \gamma (I_{t}^{n} + I_{t+1}^{n})}{1 + \frac{1}{2} (\delta + \mu_{t+1})} \\
  S_{t+1} &= \frac{(1 - \frac{1}{2} \mu_{t}) S_{t} + B_{t+1} - Z_{t+1} + \frac{1}{2} \delta (R_{t} + R_{t+1})}{1 + \frac{1}{2} \mu_{t+1}} \\
  \beta_{t} &= \frac{Z_{t} + Z_{t+1}}{2 S_{t} \sum\nolimits_{j} I_{t}^{j}}
\end{align}
\end{subequations}
%
which can be written as a linear difference equation of the form
%
\begin{equation}
\label{eq:fastbeta-linear}
x_{t+1} = L_{t} x_{t}
\end{equation}
%
where $L$ is an lower triangular coefficient matrix and
$x = (1, (E)_{i=1}^{m}, (I)_{j=1}^{n}, R, S)$.

\subsection{Arguments}

\begin{description}
\item[\code{series}] \hfill \\
  a ``multiple time series'' object, inheriting from class \code{mts},
  with three columns storing (``parallel'', equally spaced) time series
  of incidence, births, and the per capita natural mortality rate,
  in that order.
\item[\code{sigma, gamma, delta}] \hfill \\
  non-negative numbers.  \code{m*sigma}, \code{n*gamma}, and
  \code{delta} are the rates of removal from each latent, infectious,
  and recovered compartment.
\item[\code{m}] \hfill \\
  a non-negative integer indicating a number of latent stages.
\item[\code{n}] \hfill \\
  a positive integer indicating a number of infectious stages.
\item[\code{init}] \hfill \\
  a numeric vector of length \code{1+m+n+1} giving an initial state with
  compartments ordered as $(S, E, I, R)$.
\item[\code{\ldots}] \hfill \\
  optional arguments passed to \code{deconvolve}, if the first column
  of \code{series} represents \emph{observed} incidence rather than
  actual or estimated incidence.
\end{description}

\subsection{An example}

<<fastbeta-ex>>=
library(fastbeta)
data(seir.ts02, package = "fastbeta")
a <- attributes(seir.ts02)
str(seir.ts02)
# plot(seir.ts02)

## We suppose that we have perfect knowledge of incidence,
## births, and the data-generating parameters
series <- cbind(seir.ts02[, c("Z", "B")], mu = a[["mu"]](0))
colnames(series) <- c("Z", "B", "mu")

args <- c(list(series = series),
          a[c("sigma", "gamma", "delta", "m", "n", "init")])
str(args)

X <- do.call(fastbeta, args)

str(X)
## plot(X)

fig.begin(width = 6, height = 3)
plot(X[, "beta"], ylab = "Transmission rate")
lines(a[["beta"]](time(X)), col = "red") # the "truth"
fig.end()
@
\begin{figure}[h]
  \centering
  \includegraphics{\Sexpr{fig.pdf}}
  \caption{\CRANpkg{fastbeta}\code{::fastbeta} example.}
  \label{fig:fastbeta-ex}
\end{figure}

\section{Back-calculating incidence from reported incidence}

\subsection{The iteration: Richardson-Lucy deconvolution}

\subsection{Arguments}

\begin{description}
\item[\code{x}] \hfill \\
  a numeric vector of length \code{n} giving the number of infections or
  deaths reported during \code{n} observation intervals of equal
  duration.
\item[\code{prob}] \hfill \\
  a numeric vector of length \code{d+n} such that \code{prob[d+i]} is
  the probability that an infection during interval \code{i} is
  eventually reported.  \code{prob} of length 1 is recycled.
\item[\code{delay}] \hfill \\
  a numeric vector of length \code{d+1} such that \code{delay[j]} is the
  probability that an infection during interval \code{i} is reported
  during interval \code{i+j-1}, given that it is eventually reported.
  \code{delay} need not sum to 1 but must not sum to 0.
\item[\code{start}] \hfill \\
  a numeric vector of length \code{d+n} giving a starting value for the
  iteration.  \code{start[d+i]} estimates the expected number of
  infections during interval \code{i} that are eventually reported.  If
  missing, then a starting value is generated by padding \code{x} on the
  left and right with \code{d-d0} and \code{d0} zeros, choosing
  \code{d0 = which.max(delay)-1}.
\item[\code{tol}] \hfill \\
  a tolerance indicating a stopping condition.
\item[\code{iter.max}] \hfill \\
  the maximum number of iterations.
\item[\code{complete}] \hfill \\
  a logical flag indicating if the result should preserve successive
  updates to \code{start}.
\end{description}

\subsection{An example}

<<deconvolve-ex-1>>=
library(fastbeta)
set.seed(2L)
n <- 200L
d <- 50L
p <- 0.1
prob <- plogis(rlogis(d + n, location = qlogis(p), scale = 0.1))
delay <- diff(pgamma(0L:(d + 1L), 12, 0.4))

h <- function (x, a = 1, b = 1, c = 0) a * exp(-b * (x - c)^2)
ans <- floor(h(seq(-60, 60, length.out = d + n), a = 1000, b = 0.001))

x0 <- rbinom(d + n, ans, prob)
x <- tabulate(rep.int(1L:(d + n), x0) +
              sample(0L:d, size = sum(x0), replace = TRUE, prob = delay),
              d + n)[-(1L:d)]

str(D0 <- deconvolve(x, prob, delay, complete = FALSE))
str(D1 <- deconvolve(x, prob, delay, complete =  TRUE))

fig.begin(width = 6, height = 5)
matplot(-(d - 1L):n,
        cbind(x0, c(rep.int(NA, d), x), prob * D0[["value"]], p * ans),
        type = c("p", "p", "p", "l"),
        col = c(1L, 1L, 2L, 4L), pch = c(16L, 1L, 16L, NA),
        lty = c(0L, 0L, 0L, 1L), lwd = c(NA, NA, NA, 3L),
        xlab = "Time", ylab = "Count")
legend("topleft", NULL,
       c("actual", "actual+delay", "actual+delay+deconvolution", "p*h"),
       col = c(1L, 1L, 2L, 4L), pch = c(16L, 1L, 16L, NA),
       lty = c(0L, 0L, 0L, 1L), lwd = c(NA, NA, NA, 3L),
       bty = "n")
fig.end()
@
\begin{figure}[h]
  \centering
  \includegraphics{\Sexpr{fig.pdf}}
  \caption{\CRANpkg{fastbeta}\code{::deconvolve} example.}
  \label{fig:fastbeta-ex}
\end{figure}
<<deconvolve-ex-2>>=
fig.begin(width = 6, height = 3)
plot(0L:D1[["iter"]], D1[["chisq"]], xlab = "Iterations", ylab = quote(chi^2))
abline(h = 1, lty = 2L)
fig.end()
@
\begin{figure}[h]
  \centering
  \includegraphics{\Sexpr{fig.pdf}}
  \caption{\CRANpkg{fastbeta}\code{::deconvolve} example.}
  \label{fig:fastbeta-ex}
\end{figure}

\section{Using \CRANpkg{fastbeta} in conjunction with \CRANpkg{pomp}}

\section{Discussion}

\bibliography{fastbeta-ms}

\address{Mikael Jagan\\
  McMaster University\\
  1280 Main Street West, Hamilton, Ontario\\
  Canada\\
  0000-0002-3542-2938\\
  \email{jaganmn@mcmaster.ca}}

\address{David J. D. Earn\\
  McMaster University\\
  1280 Main Street West, Hamilton, Ontario\\
  Canada\\
  0000-0002-7562-1341\\
  \email{earn@math.mcmaster.ca}}

% \section{Section title in sentence case}

% Introductory section which may include references in parentheses
% \citep{R}, or cite a reference such as \citet{R} in the text.

% \section{Another section}

% This section may contain a figure such as Figure~\ref{figure:rlogo}.

% \begin{figure}[htbp]
%   \centering
%   \includegraphics{Rlogo-5}
%   \caption{The logo of R.}
%   \label{figure:rlogo}
% \end{figure}

% \section{Another section}

% There will likely be several sections, perhaps including code snippets, such as:

% \begin{example}
%   x <- 1:10
%   result <- myFunction(x)
% \end{example}

% \section{Summary}

% This file is only a basic article template. For full details of \emph{The R Journal} style and information on how to prepare your article for submission, see the \href{https://journal.r-project.org/share/author-guide.pdf}{Instructions for Authors}.
